# Only syntax enclosed in blocks can be documented

[dir]
read_dir = "./src"
read_folder = ["*"] # Can use `*`
create_dir = "./"

[read]
# Highlight
# Supported Languages => Try it out
# https://prismjs.com/index.html#supported-languages
# "Language to be loaded" (For Highlights)
read_lang = "rust"
# "Extension to be loaded"
# `ext` => OK
# `.ext` => NG
read_ext = "rs"
# Comment
# Supported symbol => `/`, `*`, `#`, `"`,`!`,
cmt_start = "///"
# Target syntax
# ["function","class",...]
target_list = ["fn","impl","enum","struct"]
modifier = ["pub"]

[exclude]
# ["Name of the file to exclude", ...]
# Pattern match from the top
exclude_file = []
exclude_folder = []

[display]
# If empty, it will be "`read_lang`doc"
create_filename = "createdoc"
# Per module or per file
is_module = true