[dir]
# read_dir = "./"
read_dir = "C:\\Users\\ohs10700\\Documents\\GitHub\\php_code-spaces\\function"
create_dir = "./"

[read]
# Highlight
# Supported Languages => php,js,rust,go
# https://prismjs.com/index.html#supported-languages
# "読み込みたい言語" (highlight)
read_lang = "php"
# "読み込みたい拡張子"
read_filename_extension = "php"
# Comment
# Supported symbol => /, *, #, ",
cmt_start = "/**"
# Target syntax
# ["function","class",...]
target = ["function"]

[exclude]
# ["除外したいファイル名", ...]
# Pattern match from the top
ex_filename = [""]
