[dir]
read_dir = "./"
create_dir = "./"

[file]
# 読み込みたいファイル名
filename = ["*"]
# 読み込みたい拡張子
filename_extension = "php"

[exclude_file]
ex_filename = [""]

# 優先度
# * < 指定
# extention < 指定
# exclude_file.指定 < file.指定