[file]
# html
create_filename = "phpdoc"

[dir]
read_dir = "./"
create_dir = "./"

[read]
# "読み込みたい拡張子"
read_filename_extension = "php"
doc_start = "/**"
doc_end = " */"


[exclude]
# ["除外したいファイル名", ...]
# ファイル名の先頭から指定
ex_filename = ["index.php"]
