[file]
# html
create_filename = "phpdoc"

[dir]
read_dir = "./"
create_dir = "./"

[read_file]
# "読み込みたい拡張子"
read_filename_extension = "php"

[exclude_file]
# ["除外したいファイル名", ...]
# ファイル名の先頭から指定
ex_filename = ["index.php"]
