[file]
# html
create_filename = "rsdoc"

[dir]
read_dir = "./"
create_dir = "./"

[read]
# 対応言語 rust,php,js
# https://prismjs.com/index.html#supported-languages
# "読み込みたい拡張子"
read_filename_extension = "php"
# コメント
cmt_start = "/**"
cmt_end = " */"
# 対象
target = ["function","class"]

[exclude]
# ["除外したいファイル名", ...]
# ファイル名の先頭から指定
ex_filename = ["index"]