[dir]
read_dir = "C:\\Users\\ohs10700\\Documents\\GitHub\\php_code-spaces\\function"
read_folder = ["int"]
create_dir = "./"

[read]
# Highlight
# Supported Languages => Try it out
# https://prismjs.com/index.html#supported-languages
# "Language to be loaded" (For Highlights)
read_lang = "php"
# "Extension to be loaded"
read_ext = "php"
# Comment
# Supported symbol => /, *, #, ",
cmt_start = "/**"
# Target syntax
# ["function","class",...]
target = ["function"]

[exclude]
# ["Name of the file to exclude", ...]
# Pattern match from the top
ex_filename = ["index"]
